//#ifndef INCLUDE_MCAL_DIO_DIO_CFG_H_
//#define INCLUDE_MCAL_DIO_DIO_CFG_H_
//
//#define PIN_INPUT  0
//#define PIN_OUTPUT 1
//
//#define PA0_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PA1_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PA2_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PA3_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PA4_INITIAL_DIRECTION 	PIN_INPUT
//#define PA5_INITIAL_DIRECTION 	PIN_INPUT
//#define PA6_INITIAL_DIRECTION 	PIN_INPUT
//#define PA7_INITIAL_DIRECTION 	PIN_INPUT
//
//#define PB0_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PB1_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PB2_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PB3_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PB4_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PB5_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PB6_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PB7_INITIAL_DIRECTION 	PIN_OUTPUT
//
//#define PC0_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PC1_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PC2_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PC3_INITIAL_DIRECTION 	PIN_INPUT
//#define PC4_INITIAL_DIRECTION 	PIN_INPUT
//#define PC5_INITIAL_DIRECTION 	PIN_INPUT
//#define PC6_INITIAL_DIRECTION 	PIN_INPUT
//#define PC7_INITIAL_DIRECTION 	PIN_INPUT
//
//#define PD0_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PD1_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PD2_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PD3_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PD4_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PD5_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PD6_INITIAL_DIRECTION 	PIN_OUTPUT
//#define PD7_INITIAL_DIRECTION 	PIN_OUTPUT
//
///*************************************************************************/
///*************************************************************************/
///*************************************************************************/
///*************************************************************************/
//
//#define PIN_FLOATING  0
//#define PIN_PULLUP    1
//
//#define PIN_LOW       0
//#define PIN_HIGH      1
//
//
//#define PA0_INITIAL_VALUE 		PIN_LOW
//#define PA1_INITIAL_VALUE 		PIN_LOW
//#define PA2_INITIAL_VALUE 		PIN_LOW
//#define PA3_INITIAL_VALUE 		PIN_LOW
//#define PA4_INITIAL_VALUE 		PIN_FLOATING
//#define PA5_INITIAL_VALUE 		PIN_FLOATING
//#define PA6_INITIAL_VALUE 		PIN_FLOATING
//#define PA7_INITIAL_VALUE 		PIN_FLOATING
//
//#define PB0_INITIAL_VALUE 		PIN_LOW
//#define PB1_INITIAL_VALUE 		PIN_LOW
//#define PB2_INITIAL_VALUE 		PIN_LOW
//#define PB3_INITIAL_VALUE 		PIN_LOW
//#define PB4_INITIAL_VALUE 		PIN_LOW
//#define PB5_INITIAL_VALUE 		PIN_LOW
//#define PB6_INITIAL_VALUE 		PIN_LOW
//#define PB7_INITIAL_VALUE 		PIN_LOW
//
//#define PC0_INITIAL_VALUE 		PIN_LOW
//#define PC1_INITIAL_VALUE 		PIN_LOW
//#define PC2_INITIAL_VALUE 		PIN_LOW
//#define PC3_INITIAL_VALUE 		PIN_FLOATING
//#define PC4_INITIAL_VALUE 		PIN_FLOATING
//#define PC5_INITIAL_VALUE 		PIN_FLOATING
//#define PC6_INITIAL_VALUE 		PIN_FLOATING
//#define PC7_INITIAL_VALUE 		PIN_FLOATING
//
//#define PD0_INITIAL_VALUE 		PIN_LOW
//#define PD1_INITIAL_VALUE 		PIN_LOW
//#define PD2_INITIAL_VALUE 		PIN_LOW
//#define PD3_INITIAL_VALUE 		PIN_LOW
//#define PD4_INITIAL_VALUE 		PIN_LOW
//#define PD5_INITIAL_VALUE 		PIN_LOW
//#define PD6_INITIAL_VALUE 		PIN_LOW
//#define PD7_INITIAL_VALUE 		PIN_LOW
//
//#endif /* INCLUDE_MCAL_DIO_DIO_CFG_H_ */

#ifndef INCLUDE_MCAL_DIO_DIO_CFG_H_
#define INCLUDE_MCAL_DIO_DIO_CFG_H_

#define PIN_INPUT 	0
#define PIN_OUTPUT	1

#define PA0_INITIAL_DIRECTION	PIN_OUTPUT
#define PA1_INITIAL_DIRECTION	PIN_OUTPUT
#define PA2_INITIAL_DIRECTION	PIN_OUTPUT
#define PA3_INITIAL_DIRECTION	PIN_OUTPUT
#define PA4_INITIAL_DIRECTION	PIN_INPUT
#define PA5_INITIAL_DIRECTION	PIN_INPUT
#define PA6_INITIAL_DIRECTION	PIN_INPUT
#define PA7_INITIAL_DIRECTION	PIN_INPUT

#define PB0_INITIAL_DIRECTION	PIN_OUTPUT
#define PB1_INITIAL_DIRECTION	PIN_OUTPUT
#define PB2_INITIAL_DIRECTION	PIN_OUTPUT
#define PB3_INITIAL_DIRECTION	PIN_INPUT
#define PB4_INITIAL_DIRECTION	PIN_INPUT
#define PB5_INITIAL_DIRECTION	PIN_INPUT
#define PB6_INITIAL_DIRECTION	PIN_INPUT
#define PB7_INITIAL_DIRECTION	PIN_INPUT

#define PC0_INITIAL_DIRECTION	PIN_OUTPUT
#define PC1_INITIAL_DIRECTION	PIN_OUTPUT
#define PC2_INITIAL_DIRECTION	PIN_OUTPUT
#define PC3_INITIAL_DIRECTION	PIN_OUTPUT
#define PC4_INITIAL_DIRECTION	PIN_OUTPUT
#define PC5_INITIAL_DIRECTION	PIN_OUTPUT
#define PC6_INITIAL_DIRECTION	PIN_OUTPUT
#define PC7_INITIAL_DIRECTION	PIN_OUTPUT

#define PD0_INITIAL_DIRECTION	PIN_INPUT
#define PD1_INITIAL_DIRECTION	PIN_INPUT
#define PD2_INITIAL_DIRECTION	PIN_INPUT
#define PD3_INITIAL_DIRECTION	PIN_INPUT
#define PD4_INITIAL_DIRECTION	PIN_INPUT
#define PD5_INITIAL_DIRECTION	PIN_INPUT
#define PD6_INITIAL_DIRECTION	PIN_INPUT
#define PD7_INITIAL_DIRECTION	PIN_INPUT

/**********************************************************/
#define PIN_FLOATING 	0
#define PIN_PULLUP  	1

#define PIN_RESET		0
#define PIN_SET		    1

#define PA0_INITIAL_VALUE	PIN_RESET
#define PA1_INITIAL_VALUE	PIN_RESET
#define PA2_INITIAL_VALUE	PIN_RESET
#define PA3_INITIAL_VALUE	PIN_RESET
#define PA4_INITIAL_VALUE	PIN_FLOATING
#define PA5_INITIAL_VALUE	PIN_FLOATING
#define PA6_INITIAL_VALUE	PIN_FLOATING
#define PA7_INITIAL_VALUE	PIN_FLOATING

#define PB0_INITIAL_VALUE	PIN_RESET
#define PB1_INITIAL_VALUE	PIN_RESET
#define PB2_INITIAL_VALUE	PIN_RESET
#define PB3_INITIAL_VALUE	PIN_RESET
#define PB4_INITIAL_VALUE	PIN_RESET
#define PB5_INITIAL_VALUE	PIN_RESET
#define PB6_INITIAL_VALUE	PIN_RESET
#define PB7_INITIAL_VALUE	PIN_RESET

#define PC0_INITIAL_VALUE	PIN_RESET
#define PC1_INITIAL_VALUE	PIN_RESET
#define PC2_INITIAL_VALUE	PIN_RESET
#define PC3_INITIAL_VALUE	PIN_FLOATING
#define PC4_INITIAL_VALUE	PIN_FLOATING
#define PC5_INITIAL_VALUE	PIN_FLOATING
#define PC6_INITIAL_VALUE	PIN_FLOATING
#define PC7_INITIAL_VALUE	PIN_FLOATING

#define PD0_INITIAL_VALUE	PIN_RESET
#define PD1_INITIAL_VALUE	PIN_RESET
#define PD2_INITIAL_VALUE	PIN_RESET
#define PD3_INITIAL_VALUE	PIN_RESET
#define PD4_INITIAL_VALUE	PIN_RESET
#define PD5_INITIAL_VALUE	PIN_RESET
#define PD6_INITIAL_VALUE	PIN_RESET
#define PD7_INITIAL_VALUE	PIN_RESET


#endif /* INCLUDE_MCAL_DIO_DIO_CFG_H_ */
