#ifndef INCLUDE_MCAL_DIO_DIO_CFG_H_
#define INCLUDE_MCAL_DIO_DIO_CFG_H_

#define PIN_INPUT 	0
#define PIN_OUTPUT	1

#define PA0_INITIAL_DIRECTION  PIN_OUTPUT
#define PA1_INITIAL_DIRECTION  PIN_OUTPUT
#define PA2_INITIAL_DIRECTION  PIN_OUTPUT
#define PA3_INITIAL_DIRECTION  PIN_OUTPUT
#define PA4_INITIAL_DIRECTION  PIN_OUTPUT
#define PA5_INITIAL_DIRECTION  PIN_OUTPUT
#define PA6_INITIAL_DIRECTION  PIN_OUTPUT
#define PA7_INITIAL_DIRECTION  PIN_OUTPUT

#define PB0_INITIAL_DIRECTION  PIN_OUTPUT
#define PB1_INITIAL_DIRECTION  PIN_OUTPUT
#define PB2_INITIAL_DIRECTION  PIN_OUTPUT
#define PB3_INITIAL_DIRECTION  PIN_INPUT
#define PB4_INITIAL_DIRECTION  PIN_OUTPUT
#define PB5_INITIAL_DIRECTION  PIN_OUTPUT
#define PB6_INITIAL_DIRECTION  PIN_OUTPUT
#define PB7_INITIAL_DIRECTION  PIN_OUTPUT

#define PC0_INITIAL_DIRECTION  PIN_INPUT
#define PC1_INITIAL_DIRECTION  PIN_INPUT
#define PC2_INITIAL_DIRECTION  PIN_INPUT
#define PC3_INITIAL_DIRECTION  PIN_INPUT
#define PC4_INITIAL_DIRECTION  PIN_INPUT
#define PC5_INITIAL_DIRECTION  PIN_INPUT
#define PC6_INITIAL_DIRECTION  PIN_INPUT
#define PC7_INITIAL_DIRECTION  PIN_INPUT

#define PD0_INITIAL_DIRECTION  PIN_INPUT
#define PD1_INITIAL_DIRECTION  PIN_OUTPUT
#define PD2_INITIAL_DIRECTION  PIN_OUTPUT
#define PD3_INITIAL_DIRECTION  PIN_OUTPUT
#define PD4_INITIAL_DIRECTION  PIN_OUTPUT
#define PD5_INITIAL_DIRECTION  PIN_OUTPUT
#define PD6_INITIAL_DIRECTION  PIN_OUTPUT
#define PD7_INITIAL_DIRECTION  PIN_INPUT

/********************************************/

#define PIN_FLOATING  0
#define PIN_PULLUP    1

#define PIN_LOW       0
#define PIN_HIGH      1


#define PA0_INITIAL_VALUE  PIN_LOW
#define PA1_INITIAL_VALUE  PIN_LOW
#define PA2_INITIAL_VALUE  PIN_LOW
#define PA3_INITIAL_VALUE  PIN_LOW
#define PA4_INITIAL_VALUE  PIN_LOW
#define PA5_INITIAL_VALUE  PIN_LOW
#define PA6_INITIAL_VALUE  PIN_LOW
#define PA7_INITIAL_VALUE  PIN_LOW

#define PB0_INITIAL_VALUE  PIN_LOW
#define PB1_INITIAL_VALUE  PIN_LOW
#define PB2_INITIAL_VALUE  PIN_LOW
#define PB3_INITIAL_VALUE  PIN_HIGH
#define PB4_INITIAL_VALUE  PIN_HIGH
#define PB5_INITIAL_VALUE  PIN_LOW
#define PB6_INITIAL_VALUE  PIN_FLOATING
#define PB7_INITIAL_VALUE  PIN_LOW

#define PC0_INITIAL_VALUE  PIN_FLOATING
#define PC1_INITIAL_VALUE  PIN_FLOATING
#define PC2_INITIAL_VALUE  PIN_FLOATING
#define PC3_INITIAL_VALUE  PIN_FLOATING
#define PC4_INITIAL_VALUE  PIN_FLOATING
#define PC5_INITIAL_VALUE  PIN_FLOATING
#define PC6_INITIAL_VALUE  PIN_FLOATING
#define PC7_INITIAL_VALUE  PIN_FLOATING

#define PD0_INITIAL_VALUE  PIN_FLOATING
#define PD1_INITIAL_VALUE  PIN_LOW
#define PD2_INITIAL_VALUE  PIN_LOW
#define PD3_INITIAL_VALUE  PIN_LOW
#define PD4_INITIAL_VALUE  PIN_LOW
#define PD5_INITIAL_VALUE  PIN_LOW
#define PD6_INITIAL_VALUE  PIN_LOW
#define PD7_INITIAL_VALUE  PIN_FLOATING


#endif /* INCLUDE_MCAL_DIO_DIO_CFG_H_ */
